---
- name: Install system libraries and dependencies (Ubuntu 24.04 LTS)
  hosts: all
  become: true
  vars:
    ansible_user: "{{ webapp_user }}"
    app_user_home: "/home/{{ webapp_user }}"

  tasks:
    # --------------------------------------------------------------------
    # APT baseline
    # --------------------------------------------------------------------
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install utility packages
      apt:
        name:
          - ca-certificates
          - curl
          - unzip
          - wget
          - gdebi-core
          - software-properties-common
        state: present

    # --------------------------------------------------------------------
    # Core build + Python environment
    # --------------------------------------------------------------------
    - name: Install compiler and Python environment tools
      apt:
        name:
          - build-essential
          - pkg-config
          - python3-dev
          - python3-pip
          - python3-venv
        state: present

    # --------------------------------------------------------------------
    # Geospatial and raster libraries (for TiTiler / Rasterio / GDAL)
    # --------------------------------------------------------------------
    - name: Install geospatial libraries
      apt:
        name:
          - gdal-bin
          - libgdal-dev
          - libproj-dev
          - proj-bin
          - proj-data
          - libgeos-dev
          - libspatialindex-dev
          - libjpeg-dev
          - libtiff-dev
          - zlib1g-dev
        state: present

    # --------------------------------------------------------------------
    # Web server (installed only, config handled later)
    # --------------------------------------------------------------------
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present

    # --------------------------------------------------------------------
    # Optional caching service
    # --------------------------------------------------------------------
    - name: Install Redis
      apt:
        name: redis-server
        state: present

    - name: Enable and start Redis service
      systemd:
        name: redis-server
        enabled: yes
        state: started

    # --------------------------------------------------------------------
    # SSH key for automation / CI
    # --------------------------------------------------------------------
    - name: Generate SSH key for application user
      openssh_keypair:
        path: "{{ app_user_home }}/.ssh/id_rsa"
        type: rsa
        size: 4096
        comment: "titiler-linode@{{ ansible_host }}"
        owner: "{{ webapp_user }}"
        group: "{{ webapp_user }}"
        mode: "0600"
      when: webapp_user != 'root'

    # --------------------------------------------------------------------
    # Cleanup
    # --------------------------------------------------------------------
    - name: Clean up unused packages
      apt:
        autoremove: yes
        purge: yes

